### ISSUE TITLE
Alignment issue in Readme.md

### ISSUE THREAD

**Issue by lubnafathima** [AccessibleForAll/Resources#13]
The code seems fine 
yet the links look like this for me:
Under **Blogs** in Readme.md
line 2
``` Hidde de Vries ``` and ``` Leonie Watson ```
is in side by side
wanted to make sure it isn't looking like this for everyone

**Comment by EmmaDawsonDev** [comment]
Ah yes, you are right. In markdown it needs 2 spaces at the end of the line to force a line break which I probably missed
