### ISSUE TITLE
[FEATURE] Add YouTube playlist

### ISSUE THREAD

**Issue by Susmita-Dey** [AccessibleForAll/Resources#2]
I want to add a YouTube playlist for **a11y** from the channel **Google Developers** in the README.md file.
Link to the playlist:- https://youtube.com/playlist?list=PLNYkxOF6rcICWx0C9LVWWVqvHlYJyqw7g

**Comment by EmmaDawsonDev** [comment]
That's a brilliant idea. Please go ahead :)
