### ISSUE TITLE
Add New Resources

### ISSUE THREAD

**Issue by tashasyarifah** [AccessibleForAll/Resources#20]
Hi,

I would like to share my resources that haven't been on lists. What should I do?

Anyway, thank you for creating this repository! I've been looking for resources about accessibility for the web. This repo is great!

**Comment by EmmaDawsonDev** [comment]
If you think they are helpful to others and want to add them to this list then please do

**Comment by tashasyarifah** [comment]
Thank you! I'll create a PR then.
