### ISSUE TITLE
Adding video links to empty section 

### ISSUE THREAD

**Issue by CBID2** [AccessibleForAll/Resources#22]
Hi there! :) I noticed that the Youtube videos (from channels without an accessibility focus) in the README file is empty, and I would like to add some links to videos in it.

**Comment by ctoffanin** [comment]
Hi, sure, go ahead!

**Comment by CBID2** [comment]
> Hi, sure, go ahead!

Hi @ctoffanin and @EmmaDawsonDev! I added the links to videos. Here's my [pull request](https://github.com/AccessibleForAll/Resources/pull/23)
