### ISSUE TITLE
feat: Add Table of Contents

### ISSUE THREAD

**Issue by anthonychinwe** [AccessibleForAll/Resources#7]
Add a `Table of Contents` section just under `Resources`, linking to each resource category section within `Readme.md`. 

This will aid navigation.

**Comment by EmmaDawsonDev** [comment]
Thanks so much for the suggestion. Github now does this automatically (if you click on the 
<img width="74" alt="image" src="https://user-images.githubusercontent.com/57045550/175791013-1e83e2cb-2970-4eb3-b03b-c1d0e1fe5ec4.png"> icon to the left of the file title.
